### ISSUE TITLE
Issue with new db-path version

### ISSUE THREAD

**Issue by Visorask** [josh-gaby/python-plexlibrary#1]
So I'm having an issue where when I run the script it will only do 2-3 movies from a trakt list. Some of the lists it will do 15 but pretty much without fail it refuses to load more than a few even when ran multiple times. Do you know what could be causing this? It says the rest of the movies in the list are missing but refuses to add them even with them in my library.

**Comment by josh-gaby** [comment]
When you say it fails to load them what do you mean? Is it not finding them in your libraries, is it finding them but not creating the symlinks, does it think that there are only a few movies in the Trakt lists?

Can you share the recipe that's failing, can you also enable the debugging option I added to the db access branch and post the output here?

You can enable the debugging option by adding the following to your recipe yml file:

```
debugging:
  enabled: true

**Comment by josh-gaby** [comment]
@Visorask any update on this issue?

**Comment by josh-gaby** [comment]
Closing this issue as there has been no update.
