### ISSUE TITLE
Python / recipe error 

### ISSUE THREAD

**Issue by ghost** [josh-gaby/python-plexlibrary#2]
Trying to run the command:
`python3 plexlibrary movies_trending`

Output is this:
https://pastebin.com/ESrvSX0y

My "trending" recipe:
https://pastebin.com/954UKxJW

It gives out this error at the end:

> 
> Traceback (most recent call last):
>   File "/usr/lib/python3.8/runpy.py", line 194, in _run_module_as_main
>     return _run_code(code, main_globals, None,
>   File "/usr/lib/python3.8/runpy.py", line 87, in _run_code
>     exec(code, run_globals)
>   File "plexlibrary/__main__.py", line 8, in <module>
>     main()
>   File "plexlibrary/plexlibrary.py", line 67, in main
>     r.run(sort_only=args.sort_only, share_playlist_to_all=args.everyone)
>   File "plexlibrary/recipe.py", line 695, in run
>     missing_items, list_count = self._run(share_playlist_to_all=share_playlist_to_all)
>   File "plexlibrary/recipe.py", line 669, in _run
>     all_new_items = self._modify_sort_titles_and_cleanup(item_list=item_list, imdb_map=imdb_map,
>   File "plexlibrary/recipe.py", line 500, in _modify_sort_titles_and_cleanup
>     self._remove_old_items_from_library(imdb_map=imdb_map)
>   File "plexlibrary/recipe.py", line 533, in _remove_old_items_from_library
>     for part in movie.files():
>   File "/home/plex/.local/lib/python3.8/site-packages/plexapi/base.py", line 296, in __getattribute__
>     value = super(PlexPartialObject, self).__getattribute__(attr)
> AttributeError: 'Movie' object has no attribute 'files'

**Comment by josh-gaby** [comment]
can you try pulling in the requirements using `pip install -r requirements.txt` it looks like you don't have the latest copy of my python-plexmovieagentmapper installed

**Comment by ghost** [comment]
Running:
`pip3 install -r requirements.txt`

Output:
https://pastebin.com/aS6fjXqZ

**Comment by josh-gaby** [comment]
Strange, I've just changed the version number of the movieagentmapper, can you try running the requirements install again?

**Comment by josh-gaby** [comment]
Ignore that, I've found the issue, working on a fix now.

**Comment by ghost** [comment]
Ah sweet. Thanks :)

**Comment by josh-gaby** [comment]
If you update to the latest version (with `git pull` if you installed via git) removal of symlinks should be working again.

**Comment by ghost** [comment]
Seems to be working now, I'll do some testing 👍
