### ISSUE TITLE
Issue with cronjob

### ISSUE THREAD

**Issue by ghost** [josh-gaby/python-plexlibrary#3]
Hey (again)

I've been having trouble running this in cron. Some days it's working fine, but others it just crashes for some reason.

The logs:
https://pastebin.com/biCtqANp

My crontab is set up like so:

> PYTHONIOENCODING=UTF-8
> LANG=en_US.UTF-8
> LC_ALL=en_US.UTF-8
> 0 */12 * * * bash /home/plex/scripts/pipLibTrending.sh
> 0 1 * * * bash /home/plex/scripts/pipLib250.sh

The individual scripts work fine, when they're running from their directory. It's just when they're run in cron, that it outputs some error(s). Can't figure out what to do next from here. 
I tried this from adamgots version: https://github.com/adamgot/python-plexlibrary/issues/69#issuecomment-573878520

That didn't work either. And **if** it works, it only works for "one cronjob" (once), and the next cronjob it fails.

## EDIT
Forgot to post the individual scripts, if that should matter:
**pipLibTrending.sh**
> #!/bin/bash​
> /usr/bin/python3 /home/plex/py3/python-plexlibrary/plexlibrary movies_trending

**pipLib250.sh**
> #!/bin/bash​
> /usr/bin/python3 /home/plex/py3/python-plexlibrary/plexlibrary movies_reddit_top_250

**Comment by josh-gaby** [comment]
I saw that a couple of times while I was setting this up, I think it was an issue with the data returned from the Trakt API being invalid.

I'll take a look and see if I can find a solution.

**Comment by josh-gaby** [comment]
@VP-EN I've changed the Trakt API connection to log the invalid response, can you pull the latest version and try again and post the output from a failed attempt?

**Comment by ghost** [comment]
I pulled the latest version, and then it doesn't give me any errors lol.

I'll just post the current / correct / right output from the cronjob(s) here anyways:
https://pastebin.com/mDd2jqSS

I'll post in here when/if it fails again 👍

**Comment by ghost** [comment]
There it goes:

> 
> 
> From plex@Engels  Fri Nov 13 01:00:02 2020
> Return-Path: <plex@Engels>
> X-Original-To: plex
> Delivered-To: plex@Engels
> Received: by Engels (Postfix, from userid 1000)
> 	id 2641458205FA; Fri, 13 Nov 2020 01:00:02 +0100 (CET)
> From: root@Engels (Cron Daemon)
> To: plex@Engels
> Subject: Cron <plex@Engels> bash /home/plex/scripts/pipLib250.sh
> MIME-Version: 1.0
> Content-Type: text/plain; charset=UTF-8
> Content-Transfer-Encoding: 8bit
> X-Cron-Env: <PYTHONIOENCODING=UTF-8>
> X-Cron-Env: <LANG=en_US.UTF-8>
> X-Cron-Env: <LC_ALL=en_US.UTF-8>
> X-Cron-Env: <SHELL=/bin/sh>
> X-Cron-Env: <HOME=/home/plex>
> X-Cron-Env: <PATH=/usr/bin:/bin>
> X-Cron-Env: <LOGNAME=plex>
> Message-Id: <20201113000002.2641458205FA@Engels>
> Date: Fri, 13 Nov 2020 01:00:02 +0100 (CET)
> 
> Traceback (most recent call last):
>   File "/usr/lib/python3.8/runpy.py", line 194, in _run_module_as_main
>     return _run_code(code, main_globals, None,
>   File "/usr/lib/python3.8/runpy.py", line 87, in _run_code
>     exec(code, run_globals)
>   File "/home/plex/py3/python-plexlibrary/plexlibrary/__main__.py", line 8, in <module>
>     main()
>   File "/home/plex/py3/python-plexlibrary/plexlibrary/plexlibrary.py", line 66, in main
>     r = Recipe(recipe_name=args.recipe, use_playlists=args.playlists)
>   File "/home/plex/py3/python-plexlibrary/plexlibrary/recipe.py", line 100, in __init__
>     self.trakt = traktutils.Trakt(
>   File "/home/plex/py3/python-plexlibrary/plexlibrary/traktutils.py", line 24, in __init__
>     trakt.core.pin_auth(username, client_id=client_id,
>   File "/home/plex/.local/lib/python3.8/site-packages/trakt/core.py", line 136, in pin_auth
>     OAUTH_TOKEN = response.json().get('access_token', None)
>   File "/home/plex/.local/lib/python3.8/site-packages/requests/models.py", line 898, in json
>     return complexjson.loads(self.text, **kwargs)
>   File "/usr/lib/python3.8/json/__init__.py", line 357, in loads
>     return _default_decoder.decode(s)
>   File "/usr/lib/python3.8/json/decoder.py", line 337, in decode
>     obj, end = self.raw_decode(s, idx=_w(s, 0).end())
>   File "/usr/lib/python3.8/json/decoder.py", line 355, in raw_decode
>     raise JSONDecodeError("Expecting value", s, err.value) from None
> json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

**Comment by josh-gaby** [comment]
@VP-EN that error seems to point to an unhandled exception in the [Trakt API module](https://pypi.org/project/trakt/), I have made some changes to hopefully handle that issue a bit nicer. If this situation happens again my changes should catch the error, add a 10 second delay and make the Trakt API call again, if it still fails after that then plexlibrary will exit with an error.

**Comment by ghost** [comment]
Sweet. I'll do a `git pull` and see if the error happens again at some point :) I'll close the issue for now
